version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # - gosec TODO: enable when fixed
    # - bodyclose TODO: enable when fixed
    # - depguard
    # - revive TODO: enable when fixed
    # - stylecheck TODO: enable when fixed
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
            - github.com/stackvista
    funlen:
      lines: 100
      statements: 60
    lll:
      line-length: 250
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-specific: true
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
