project_name: stackstate-cli
release:
  gitlab:
    owner: stackvista
    name: "{{ .ProjectName }}"
  name_template: '{{.Tag}}'
  disable: true
before:
  hooks:
    - go mod download
builds:
- id: stackstate-cli-full
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/cmd.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Date={{.Date}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.CLIType=full
    -X main.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
- id: stackstate-cli-saas
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/cmd.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Date={{.Date}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.CLIType=saas
    -X main.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- id: stackstate-cli-full
  builds:
  - stackstate-cli-full
  name_template: '{{ .ProjectName }}-full-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
- id: stackstate-cli-saas
  builds:
  - stackstate-cli-saas
  name_template: '{{ .ProjectName }}-saas-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
blobs:
  - provider: s3
    bucket: cli-dl.stackstate.com
    ids:
      - stackstate-cli-full
      - stackstate-cli-saas
brews:
- name: stackstate-cli
  ids:
    - stackstate-cli-full
  tap:
    owner: stackvista
    name: homebrew-tap
  commit_author:
    name: stackstatebot
    email: sts-admin@stackstate.com
  folder: Formula
  install: |
    bin.install "sts"
  test: |
    system "#{bin}/sts", "version"
  description: StackState CLI
  homepage: https://docs.stackstate.com
  url_template: https://dl.stackstate.com/{{ .ProjectName }}/{{.Tag}}/{{ .ArtifactName }}
  goarm: "6"
