project_name: stackstate-cli
release:
  github:
    owner: stackvista
    name: stackstate-cli
  name_template: '{{.Tag}}'
before:
  hooks:
    - go mod download
builds:
- id: stackstate-cli
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X github.com/stackvista/stackstate-cli/static_info.Version={{.Version}}
    -X github.com/stackvista/stackstate-cli/static_info.Commit={{.Commit}}
    -X github.com/stackvista/stackstate-cli/static_info.BuildDate={{.Date}}
    -X static_info.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- id: stackstate-cli
  builds:
  - stackstate-cli
  name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
blobs:
  - provider: s3
    bucket: cli-dl.stackstate.com
    ids:
      - stackstate-cli
dockers:
- image_templates:
  - "stackstate/stackstate-cli2:{{ .Version }}-x86_64"
  ids:
    - stackstate-cli
  use: buildx
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--provenance=false"
- image_templates:
  - "stackstate/stackstate-cli2:{{ .Version }}-arm64v8"
  ids:
    - stackstate-cli
  use: buildx
  goarch: arm64
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--provenance=false"
docker_manifests:
- name_template: stackstate/stackstate-cli2:{{ .Version }}
  image_templates:
  - stackstate/stackstate-cli2:{{ .Version }}-x86_64
  - stackstate/stackstate-cli2:{{ .Version }}-arm64v8
- name_template: stackstate/stackstate-cli2:latest
  image_templates:
  - stackstate/stackstate-cli2:{{ .Version }}-x86_64
  - stackstate/stackstate-cli2:{{ .Version }}-arm64v8
