# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: StackPack API
  version: "1.0.0"
paths:
  /stackpack:
    post:
      tags:
        - stackpack
      summary: "StackPack API"
      operationId: stackpackUpload
      description: "upload a StackPack"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/StackPackUpload"
      responses:
        "202":
          description: "Upload success. Processing happens asynchronously."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackPack"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
    get:
      tags:
        - stackpack
      summary: "StackPack API"
      operationId: stackpackList
      description: "list of stackpack"
      responses:
        "200":
          description: "Get list of stackpack"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StackpackList"
        "400":
          description: "bad request"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /stackpack/{stackName}/provision:
    post:
      tags:
        - stackpack
      parameters:
        - $ref: "#/components/parameters/stackName"
      summary: "Provision API"
      operationId: provisionDetails
      description: "Provision details"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
      responses:
        "200":
          description: "Successful provisioning of the stackpack"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvisionResponse"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  parameters:
    stackName:
      in: path
      name: stackName
      required: true
      schema:
        $ref: "#/components/schemas/stackName"

  schemas:
    StackPackUpload:
      type: object
      properties:
        stackPack:
          type: string
          format: binary
    StackPack:
      type: object
      required:
        - name
        - displayName
        - version
        - categories
        - isNew
        - releaseStatus
        - isCompatible
      properties:
        name:
          type: string
        displayName:
          type: string
        version:
          type: string
        logo:
          type: string
        categories:
          type: array
          items:
            type: string
        isNew:
          type: boolean
        overviewUrl:
          type: string
        detailedOverviewUrl:
          type: string
        resourcesUrl:
          type: string
        faqs:
          type: array
          items:
            type: object
            required:
              - question
              - answer
            properties:
              question:
                type: string
              answer:
                type: string
        configurationUrls:
          type: array
          items:
            type: array
            items:
              type: string
        releaseStatus:
          type: string
          enum:
            - AVAILABLE
            - ENABLED
            - COMING_SOON
            - HIDDEN
            - BROKEN
        isCompatible: 
          type: boolean

    StackPackStep:
      type: object
      properties:
        display:
          type: string
        name:
          type: string
        value:
          type: object
          properties:
            _type:
              type: string

    StackpackList:
      type: array
      items:
        $ref: "#/components/schemas/Sstackpack"

    Sstackpack:
      type: object
      properties:
        name:
          type: string
        displayName:
          type: string
        version:
          type: string
        configurations:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
              status:
                type: string
              lastUpdateTimestamp:
                type: integer
                format: int64
              stackPackVersion:
                type: string
            required:
              - lastUpdateTimestamp
        latestVersion:
          type: object
          properties:
            version:
              type: string
        nextVersion:
          type: object
          properties:
            version:
              type: string
        steps:
           type: array
           items:
             $ref: "#/components/schemas/StackPackStep"

    stackName:
      type: string
    ProvisionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
        name:
          type: string
        stackPackVersion:
          type: string
        lastUpdateTimestamp:
          type: integer
          format: int64
