# OpenApi header is included in this file to support code highlighting in VSCode
openapi: 3.0.3
info:
  title: User Profile API
  version: "1.0.0"
paths:
  /user/profile:
    get:
      tags:
        - userProfile
      summary: "Get current user profile"
      description: "Get current user profile."
      operationId: getCurrentUserProfile
      responses:
        "200":
          $ref: "#/components/responses/userProfile"
        "400":
          description: Get User Profile Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
    put:
      tags:
        - userProfile
      summary: "Save current user profile"
      description: "Save current user profile."
      operationId: saveCurrentUserProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfile"
      responses:
        "200":
          $ref: "#/components/responses/userProfile"
        "400":
          description: Save User Profile Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfileSaveError"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
  /user/profile/tokens:
    get:
      tags:
        - apiToken
      summary: "Get current user's API tokens"
      description: "Get all API token of the logged-in user."
      operationId: getCurrentUserApiTokens
      responses:
        "200":
          $ref: "#/components/responses/apiTokens"
        "400":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserNotFoundError"
        "500":
          $ref: "generic_error_handling.xapi.yaml#/components/responses/genericErrorsResponse"
components:
  responses:
    userProfile:
      description: User Profile
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UserProfile"
    apiTokens:
      description: Api Token
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ApiToken"
  schemas:
    UserNameMismatchError:
      type: object
      properties:
        _type:
          type: string
          enum:
            - UserNameMismatchError
        name:
          type: string
      required:
        - name
        - _type
    UserNotLoggedInError:
      type: object
      properties:
        _type:
          type: string
          enum:
            - UserNotLoggedInError
      required:
        - _type
    UserNotFoundError:
      type: object
      properties:
        _type:
          type: string
          enum:
            - UserNotFoundError
        name:
          type: string
      required:
        - name
        - _type
    UserProfileSaveError:
      discriminator:
        propertyName: _type
      oneOf:
        - $ref: "#/components/schemas/UserNameMismatchError"
        - $ref: "#/components/schemas/UserNotFoundError"
        - $ref: "#/components/schemas/UserNotLoggedInError"
      required:
        - _type
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        lastUpdateTimestamp:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        description:
          type: string
        identifier:
          type: string
        starredViews:
          type: array
          items:
            type: integer
            format: int64
        ownedBy:
          type: string
      required:
        - name
    ApiToken:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        lastUpdateTimestamp:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
        description:
          type: string
        token:
          type: string
      required:
        - name
        - token
