/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
)


type MonitorUrnApi interface {

	/*
	DeleteMonitorByURN Delete a monitor

	Deletes existing monitor

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param monitorUrnId The identifier of a monitor
	@return ApiDeleteMonitorByURNRequest
	*/
	DeleteMonitorByURN(ctx context.Context, monitorUrnId string) ApiDeleteMonitorByURNRequest

	// DeleteMonitorByURNExecute executes the request
	DeleteMonitorByURNExecute(r ApiDeleteMonitorByURNRequest) (*http.Response, error)

	/*
	DryRunMonitorByURN Dry run a monitor and show a result

	Performs a dry run of a monitor without topology state modification

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param monitorUrnId The identifier of a monitor
	@return ApiDryRunMonitorByURNRequest
	*/
	DryRunMonitorByURN(ctx context.Context, monitorUrnId string) ApiDryRunMonitorByURNRequest

	// DryRunMonitorByURNExecute executes the request
	//  @return MonitorRunResult
	DryRunMonitorByURNExecute(r ApiDryRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error)

	/*
	GetMonitorByURN Get a monitor

	Returns a monitor full representation

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param monitorUrnId The identifier of a monitor
	@return ApiGetMonitorByURNRequest
	*/
	GetMonitorByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorByURNRequest

	// GetMonitorByURNExecute executes the request
	//  @return Monitor
	GetMonitorByURNExecute(r ApiGetMonitorByURNRequest) (*Monitor, *http.Response, error)

	/*
	GetMonitorWithStatusByURN Get a monitor with stream information

	Returns a monitor full representation with the stream status information

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param monitorUrnId The identifier of a monitor
	@return ApiGetMonitorWithStatusByURNRequest
	*/
	GetMonitorWithStatusByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorWithStatusByURNRequest

	// GetMonitorWithStatusByURNExecute executes the request
	//  @return MonitorStatus
	GetMonitorWithStatusByURNExecute(r ApiGetMonitorWithStatusByURNRequest) (*MonitorStatus, *http.Response, error)

	/*
	RunMonitorByURN Run a monitor

	Runs a monitor once

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param monitorUrnId The identifier of a monitor
	@return ApiRunMonitorByURNRequest
	*/
	RunMonitorByURN(ctx context.Context, monitorUrnId string) ApiRunMonitorByURNRequest

	// RunMonitorByURNExecute executes the request
	//  @return MonitorRunResult
	RunMonitorByURNExecute(r ApiRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error)
}

// MonitorUrnApiService MonitorUrnApi service
type MonitorUrnApiService service

type ApiDeleteMonitorByURNRequest struct {
	ctx context.Context
	ApiService MonitorUrnApi
	monitorUrnId string
}

func (r ApiDeleteMonitorByURNRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteMonitorByURNExecute(r)
}

/*
DeleteMonitorByURN Delete a monitor

Deletes existing monitor

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param monitorUrnId The identifier of a monitor
 @return ApiDeleteMonitorByURNRequest
*/
func (a *MonitorUrnApiService) DeleteMonitorByURN(ctx context.Context, monitorUrnId string) ApiDeleteMonitorByURNRequest {
	return ApiDeleteMonitorByURNRequest{
		ApiService: a,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

// Execute executes the request
func (a *MonitorUrnApiService) DeleteMonitorByURNExecute(r ApiDeleteMonitorByURNRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitorUrnApiService.DeleteMonitorByURN")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/monitorUrn/{monitorUrnId}"
	localVarPath = strings.Replace(localVarPath, "{"+"monitorUrnId"+"}", url.PathEscape(parameterToString(r.monitorUrnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v MonitorIdentifierNotFoundError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v MonitorApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDryRunMonitorByURNRequest struct {
	ctx context.Context
	ApiService MonitorUrnApi
	monitorUrnId string
}

func (r ApiDryRunMonitorByURNRequest) Execute() (*MonitorRunResult, *http.Response, error) {
	return r.ApiService.DryRunMonitorByURNExecute(r)
}

/*
DryRunMonitorByURN Dry run a monitor and show a result

Performs a dry run of a monitor without topology state modification

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param monitorUrnId The identifier of a monitor
 @return ApiDryRunMonitorByURNRequest
*/
func (a *MonitorUrnApiService) DryRunMonitorByURN(ctx context.Context, monitorUrnId string) ApiDryRunMonitorByURNRequest {
	return ApiDryRunMonitorByURNRequest{
		ApiService: a,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

// Execute executes the request
//  @return MonitorRunResult
func (a *MonitorUrnApiService) DryRunMonitorByURNExecute(r ApiDryRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MonitorRunResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitorUrnApiService.DryRunMonitorByURN")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/monitorUrn/{monitorUrnId}/dryRun"
	localVarPath = strings.Replace(localVarPath, "{"+"monitorUrnId"+"}", url.PathEscape(parameterToString(r.monitorUrnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v MonitorIdentifierNotFoundError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v MonitorApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMonitorByURNRequest struct {
	ctx context.Context
	ApiService MonitorUrnApi
	monitorUrnId string
}

func (r ApiGetMonitorByURNRequest) Execute() (*Monitor, *http.Response, error) {
	return r.ApiService.GetMonitorByURNExecute(r)
}

/*
GetMonitorByURN Get a monitor

Returns a monitor full representation

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param monitorUrnId The identifier of a monitor
 @return ApiGetMonitorByURNRequest
*/
func (a *MonitorUrnApiService) GetMonitorByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorByURNRequest {
	return ApiGetMonitorByURNRequest{
		ApiService: a,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

// Execute executes the request
//  @return Monitor
func (a *MonitorUrnApiService) GetMonitorByURNExecute(r ApiGetMonitorByURNRequest) (*Monitor, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Monitor
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitorUrnApiService.GetMonitorByURN")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/monitorUrn/{monitorUrnId}"
	localVarPath = strings.Replace(localVarPath, "{"+"monitorUrnId"+"}", url.PathEscape(parameterToString(r.monitorUrnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v MonitorIdentifierNotFoundError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v MonitorApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMonitorWithStatusByURNRequest struct {
	ctx context.Context
	ApiService MonitorUrnApi
	monitorUrnId string
}

func (r ApiGetMonitorWithStatusByURNRequest) Execute() (*MonitorStatus, *http.Response, error) {
	return r.ApiService.GetMonitorWithStatusByURNExecute(r)
}

/*
GetMonitorWithStatusByURN Get a monitor with stream information

Returns a monitor full representation with the stream status information

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param monitorUrnId The identifier of a monitor
 @return ApiGetMonitorWithStatusByURNRequest
*/
func (a *MonitorUrnApiService) GetMonitorWithStatusByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorWithStatusByURNRequest {
	return ApiGetMonitorWithStatusByURNRequest{
		ApiService: a,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

// Execute executes the request
//  @return MonitorStatus
func (a *MonitorUrnApiService) GetMonitorWithStatusByURNExecute(r ApiGetMonitorWithStatusByURNRequest) (*MonitorStatus, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MonitorStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitorUrnApiService.GetMonitorWithStatusByURN")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/monitorUrn/{monitorUrnId}/status"
	localVarPath = strings.Replace(localVarPath, "{"+"monitorUrnId"+"}", url.PathEscape(parameterToString(r.monitorUrnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v MonitorIdentifierNotFoundError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v MonitorApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRunMonitorByURNRequest struct {
	ctx context.Context
	ApiService MonitorUrnApi
	monitorUrnId string
}

func (r ApiRunMonitorByURNRequest) Execute() (*MonitorRunResult, *http.Response, error) {
	return r.ApiService.RunMonitorByURNExecute(r)
}

/*
RunMonitorByURN Run a monitor

Runs a monitor once

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param monitorUrnId The identifier of a monitor
 @return ApiRunMonitorByURNRequest
*/
func (a *MonitorUrnApiService) RunMonitorByURN(ctx context.Context, monitorUrnId string) ApiRunMonitorByURNRequest {
	return ApiRunMonitorByURNRequest{
		ApiService: a,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

// Execute executes the request
//  @return MonitorRunResult
func (a *MonitorUrnApiService) RunMonitorByURNExecute(r ApiRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *MonitorRunResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitorUrnApiService.RunMonitorByURN")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/monitorUrn/{monitorUrnId}/run"
	localVarPath = strings.Replace(localVarPath, "{"+"monitorUrnId"+"}", url.PathEscape(parameterToString(r.monitorUrnId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v MonitorIdentifierNotFoundError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v MonitorApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}


// ---------------------------------------------
// ------------------ MOCKS --------------------
// ---------------------------------------------


type MonitorUrnApiMock struct {
	DeleteMonitorByURNCalls *[]DeleteMonitorByURNCall
	DeleteMonitorByURNResponse DeleteMonitorByURNMockResponse
	DryRunMonitorByURNCalls *[]DryRunMonitorByURNCall
	DryRunMonitorByURNResponse DryRunMonitorByURNMockResponse
	GetMonitorByURNCalls *[]GetMonitorByURNCall
	GetMonitorByURNResponse GetMonitorByURNMockResponse
	GetMonitorWithStatusByURNCalls *[]GetMonitorWithStatusByURNCall
	GetMonitorWithStatusByURNResponse GetMonitorWithStatusByURNMockResponse
	RunMonitorByURNCalls *[]RunMonitorByURNCall
	RunMonitorByURNResponse RunMonitorByURNMockResponse
}	

func NewMonitorUrnApiMock() MonitorUrnApiMock {
	xDeleteMonitorByURNCalls := make([]DeleteMonitorByURNCall, 0)
	xDryRunMonitorByURNCalls := make([]DryRunMonitorByURNCall, 0)
	xGetMonitorByURNCalls := make([]GetMonitorByURNCall, 0)
	xGetMonitorWithStatusByURNCalls := make([]GetMonitorWithStatusByURNCall, 0)
	xRunMonitorByURNCalls := make([]RunMonitorByURNCall, 0)
	return MonitorUrnApiMock {
		DeleteMonitorByURNCalls: &xDeleteMonitorByURNCalls,
		DryRunMonitorByURNCalls: &xDryRunMonitorByURNCalls,
		GetMonitorByURNCalls: &xGetMonitorByURNCalls,
		GetMonitorWithStatusByURNCalls: &xGetMonitorWithStatusByURNCalls,
		RunMonitorByURNCalls: &xRunMonitorByURNCalls,
	}
}

type DeleteMonitorByURNMockResponse struct {
	
	Response *http.Response
	Error error
}

type DeleteMonitorByURNCall struct {
	PmonitorUrnId string
}


func (mock MonitorUrnApiMock) DeleteMonitorByURN(ctx context.Context, monitorUrnId string) ApiDeleteMonitorByURNRequest {
	return ApiDeleteMonitorByURNRequest{
		ApiService: mock,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

func (mock MonitorUrnApiMock) DeleteMonitorByURNExecute(r ApiDeleteMonitorByURNRequest) (*http.Response, error) {
	p := DeleteMonitorByURNCall {
			PmonitorUrnId: r.monitorUrnId,
	}
	*mock.DeleteMonitorByURNCalls = append(*mock.DeleteMonitorByURNCalls, p)
	return mock.DeleteMonitorByURNResponse.Response, mock.DeleteMonitorByURNResponse.Error
}

type DryRunMonitorByURNMockResponse struct {
	Result MonitorRunResult
	Response *http.Response
	Error error
}

type DryRunMonitorByURNCall struct {
	PmonitorUrnId string
}


func (mock MonitorUrnApiMock) DryRunMonitorByURN(ctx context.Context, monitorUrnId string) ApiDryRunMonitorByURNRequest {
	return ApiDryRunMonitorByURNRequest{
		ApiService: mock,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

func (mock MonitorUrnApiMock) DryRunMonitorByURNExecute(r ApiDryRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error) {
	p := DryRunMonitorByURNCall {
			PmonitorUrnId: r.monitorUrnId,
	}
	*mock.DryRunMonitorByURNCalls = append(*mock.DryRunMonitorByURNCalls, p)
	return &mock.DryRunMonitorByURNResponse.Result, mock.DryRunMonitorByURNResponse.Response, mock.DryRunMonitorByURNResponse.Error
}

type GetMonitorByURNMockResponse struct {
	Result Monitor
	Response *http.Response
	Error error
}

type GetMonitorByURNCall struct {
	PmonitorUrnId string
}


func (mock MonitorUrnApiMock) GetMonitorByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorByURNRequest {
	return ApiGetMonitorByURNRequest{
		ApiService: mock,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

func (mock MonitorUrnApiMock) GetMonitorByURNExecute(r ApiGetMonitorByURNRequest) (*Monitor, *http.Response, error) {
	p := GetMonitorByURNCall {
			PmonitorUrnId: r.monitorUrnId,
	}
	*mock.GetMonitorByURNCalls = append(*mock.GetMonitorByURNCalls, p)
	return &mock.GetMonitorByURNResponse.Result, mock.GetMonitorByURNResponse.Response, mock.GetMonitorByURNResponse.Error
}

type GetMonitorWithStatusByURNMockResponse struct {
	Result MonitorStatus
	Response *http.Response
	Error error
}

type GetMonitorWithStatusByURNCall struct {
	PmonitorUrnId string
}


func (mock MonitorUrnApiMock) GetMonitorWithStatusByURN(ctx context.Context, monitorUrnId string) ApiGetMonitorWithStatusByURNRequest {
	return ApiGetMonitorWithStatusByURNRequest{
		ApiService: mock,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

func (mock MonitorUrnApiMock) GetMonitorWithStatusByURNExecute(r ApiGetMonitorWithStatusByURNRequest) (*MonitorStatus, *http.Response, error) {
	p := GetMonitorWithStatusByURNCall {
			PmonitorUrnId: r.monitorUrnId,
	}
	*mock.GetMonitorWithStatusByURNCalls = append(*mock.GetMonitorWithStatusByURNCalls, p)
	return &mock.GetMonitorWithStatusByURNResponse.Result, mock.GetMonitorWithStatusByURNResponse.Response, mock.GetMonitorWithStatusByURNResponse.Error
}

type RunMonitorByURNMockResponse struct {
	Result MonitorRunResult
	Response *http.Response
	Error error
}

type RunMonitorByURNCall struct {
	PmonitorUrnId string
}


func (mock MonitorUrnApiMock) RunMonitorByURN(ctx context.Context, monitorUrnId string) ApiRunMonitorByURNRequest {
	return ApiRunMonitorByURNRequest{
		ApiService: mock,
		ctx: ctx,
		monitorUrnId: monitorUrnId,
	}
}

func (mock MonitorUrnApiMock) RunMonitorByURNExecute(r ApiRunMonitorByURNRequest) (*MonitorRunResult, *http.Response, error) {
	p := RunMonitorByURNCall {
			PmonitorUrnId: r.monitorUrnId,
	}
	*mock.RunMonitorByURNCalls = append(*mock.RunMonitorByURNCalls, p)
	return &mock.RunMonitorByURNResponse.Result, mock.RunMonitorByURNResponse.Response, mock.RunMonitorByURNResponse.Error
}


