/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

type ImportApi interface {

	/*
	ImportSettings Import settings

	Import StackState Templated JSON (STJ) setting nodes.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @return ApiImportSettingsRequest
	*/
	ImportSettings(ctx _context.Context) ApiImportSettingsRequest

	// ImportSettingsExecute executes the request
	//  @return []map[string]interface{}
	ImportSettingsExecute(r ApiImportSettingsRequest) ([]map[string]interface{}, *_nethttp.Response, error)
}


// ImportApiService ImportApi service
type ImportApiService service

type ApiImportSettingsRequest struct {
	ctx _context.Context
	ApiService ImportApi
	body *string
	timeoutSeconds *int32
	namespace *string
	unlocked *string
}

func (r ApiImportSettingsRequest) Body(body string) ApiImportSettingsRequest {
	r.body = &body
	return r
}
func (r ApiImportSettingsRequest) TimeoutSeconds(timeoutSeconds int32) ApiImportSettingsRequest {
	r.timeoutSeconds = &timeoutSeconds
	return r
}
func (r ApiImportSettingsRequest) Namespace(namespace string) ApiImportSettingsRequest {
	r.namespace = &namespace
	return r
}
func (r ApiImportSettingsRequest) Unlocked(unlocked string) ApiImportSettingsRequest {
	r.unlocked = &unlocked
	return r
}

func (r ApiImportSettingsRequest) Execute() ([]map[string]interface{}, *_nethttp.Response, error) {
	return r.ApiService.ImportSettingsExecute(r)
}

/*
ImportSettings Import settings

Import StackState Templated JSON (STJ) setting nodes.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiImportSettingsRequest
*/
func (a *ImportApiService) ImportSettings(ctx _context.Context) ApiImportSettingsRequest {
	return ApiImportSettingsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []map[string]interface{}
func (a *ImportApiService) ImportSettingsExecute(r ApiImportSettingsRequest) ([]map[string]interface{}, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  []map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ImportApiService.ImportSettings")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/import"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	if r.timeoutSeconds != nil {
		localVarQueryParams.Add("timeoutSeconds", parameterToString(*r.timeoutSeconds, ""))
	}
	if r.namespace != nil {
		localVarQueryParams.Add("namespace", parameterToString(*r.namespace, ""))
	}
	if r.unlocked != nil {
		localVarQueryParams.Add("unlocked", parameterToString(*r.unlocked, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"plain/text"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v GenericErrorsResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v GenericErrorsResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}


// ---------------------------------------------
// ------------------ MOCKS --------------------
// ---------------------------------------------


type ImportApiMock struct {
	ImportSettingsCalls *[]ImportSettingsCall
	ImportSettingsResponse ImportSettingsMockResponse
}	

func NewImportApiMock() ImportApiMock {
	xImportSettingsCalls := make([]ImportSettingsCall, 0)
	return ImportApiMock {
		ImportSettingsCalls: &xImportSettingsCalls,
	}
}

type ImportSettingsMockResponse struct {
	Result []map[string]interface{}
	Response *_nethttp.Response
	Error error
}

type ImportSettingsCall struct {
	Pbody *string
	PtimeoutSeconds *int32
	Pnamespace *string
	Punlocked *string
}


func (mock ImportApiMock) ImportSettings(ctx _context.Context) ApiImportSettingsRequest {
	return ApiImportSettingsRequest{
		ApiService: mock,
		ctx: ctx,
	}
}

func (mock ImportApiMock) ImportSettingsExecute(r ApiImportSettingsRequest) ([]map[string]interface{}, *_nethttp.Response, error) {
	p := ImportSettingsCall {
			Pbody: r.body,
			PtimeoutSeconds: r.timeoutSeconds,
			Pnamespace: r.namespace,
			Punlocked: r.unlocked,
	}
	*mock.ImportSettingsCalls = append(*mock.ImportSettingsCalls, p)
	return mock.ImportSettingsResponse.Result, mock.ImportSettingsResponse.Response, mock.ImportSettingsResponse.Error
}


