/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

type HealthSynchronizationApi interface {

	/*
	DeleteHealthSynchronizationStream Delete health sync stream

	Delete a health synchronization stream. Deletion will not be immediate.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @return ApiDeleteHealthSynchronizationStreamRequest
	*/
	DeleteHealthSynchronizationStream(ctx _context.Context, healthStreamUrn string) ApiDeleteHealthSynchronizationStreamRequest

	// DeleteHealthSynchronizationStreamExecute executes the request
	DeleteHealthSynchronizationStreamExecute(r ApiDeleteHealthSynchronizationStreamRequest) (*_nethttp.Response, error)

	/*
	GetHealthSynchronizationStreamStatus Get health sync stream status

	Status overview of a single health synchronization stream

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @return ApiGetHealthSynchronizationStreamStatusRequest
	*/
	GetHealthSynchronizationStreamStatus(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamStatusRequest

	// GetHealthSynchronizationStreamStatusExecute executes the request
	//  @return HealthStreamStatus
	GetHealthSynchronizationStreamStatusExecute(r ApiGetHealthSynchronizationStreamStatusRequest) (HealthStreamStatus, *_nethttp.Response, error)

	/*
	GetHealthSynchronizationStreamTopologyMatches List health sync stream check-states

	Overview of check-states matched to topology on the main stream.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @return ApiGetHealthSynchronizationStreamTopologyMatchesRequest
	*/
	GetHealthSynchronizationStreamTopologyMatches(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamTopologyMatchesRequest

	// GetHealthSynchronizationStreamTopologyMatchesExecute executes the request
	//  @return TopologyMatchResult
	GetHealthSynchronizationStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error)

	/*
	GetHealthSynchronizationStreamsOverview List health sync streams

	Status overview of the health synchronization streams.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @return ApiGetHealthSynchronizationStreamsOverviewRequest
	*/
	GetHealthSynchronizationStreamsOverview(ctx _context.Context) ApiGetHealthSynchronizationStreamsOverviewRequest

	// GetHealthSynchronizationStreamsOverviewExecute executes the request
	//  @return StreamList
	GetHealthSynchronizationStreamsOverviewExecute(r ApiGetHealthSynchronizationStreamsOverviewRequest) (StreamList, *_nethttp.Response, error)

	/*
	GetHealthSynchronizationSubStreamOverview List health sync sub-streams

	Overview of all sub-streams in a certain health stream.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @return ApiGetHealthSynchronizationSubStreamOverviewRequest
	*/
	GetHealthSynchronizationSubStreamOverview(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationSubStreamOverviewRequest

	// GetHealthSynchronizationSubStreamOverviewExecute executes the request
	//  @return SubStreamList
	GetHealthSynchronizationSubStreamOverviewExecute(r ApiGetHealthSynchronizationSubStreamOverviewRequest) (SubStreamList, *_nethttp.Response, error)

	/*
	GetHealthSynchronizationSubStreamStatus Get health sync sub-stream status

	Status overview of a single health synchronization sub stream

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @param healthSyncSubStreamId Health synchronization sub stream id.
	 @return ApiGetHealthSynchronizationSubStreamStatusRequest
	*/
	GetHealthSynchronizationSubStreamStatus(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamStatusRequest

	// GetHealthSynchronizationSubStreamStatusExecute executes the request
	//  @return HealthSubStreamStatus
	GetHealthSynchronizationSubStreamStatusExecute(r ApiGetHealthSynchronizationSubStreamStatusRequest) (HealthSubStreamStatus, *_nethttp.Response, error)

	/*
	GetHealthSynchronizationSubStreamTopologyMatches List health sync sub-stream check-states

	Overview of check-states matched to topology on the main stream.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @param healthSyncSubStreamId Health synchronization sub stream id.
	 @return ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest
	*/
	GetHealthSynchronizationSubStreamTopologyMatches(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest

	// GetHealthSynchronizationSubStreamTopologyMatchesExecute executes the request
	//  @return TopologyMatchResult
	GetHealthSynchronizationSubStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error)

	/*
	PostHealthSynchronizationStreamClearErrors Clear health sync stream errors

	Clear all errors for a stream and its sub-streams.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param healthStreamUrn Urn of the health stream.
	 @return ApiPostHealthSynchronizationStreamClearErrorsRequest
	*/
	PostHealthSynchronizationStreamClearErrors(ctx _context.Context, healthStreamUrn string) ApiPostHealthSynchronizationStreamClearErrorsRequest

	// PostHealthSynchronizationStreamClearErrorsExecute executes the request
	PostHealthSynchronizationStreamClearErrorsExecute(r ApiPostHealthSynchronizationStreamClearErrorsRequest) (*_nethttp.Response, error)
}

type HealthSynchronizationApiMock struct {
	DeleteHealthSynchronizationStreamCalls *[]DeleteHealthSynchronizationStreamCall
	DeleteHealthSynchronizationStreamResponse DeleteHealthSynchronizationStreamMockResponse
	GetHealthSynchronizationStreamStatusCalls *[]GetHealthSynchronizationStreamStatusCall
	GetHealthSynchronizationStreamStatusResponse GetHealthSynchronizationStreamStatusMockResponse
	GetHealthSynchronizationStreamTopologyMatchesCalls *[]GetHealthSynchronizationStreamTopologyMatchesCall
	GetHealthSynchronizationStreamTopologyMatchesResponse GetHealthSynchronizationStreamTopologyMatchesMockResponse
	GetHealthSynchronizationStreamsOverviewCalls *[]GetHealthSynchronizationStreamsOverviewCall
	GetHealthSynchronizationStreamsOverviewResponse GetHealthSynchronizationStreamsOverviewMockResponse
	GetHealthSynchronizationSubStreamOverviewCalls *[]GetHealthSynchronizationSubStreamOverviewCall
	GetHealthSynchronizationSubStreamOverviewResponse GetHealthSynchronizationSubStreamOverviewMockResponse
	GetHealthSynchronizationSubStreamStatusCalls *[]GetHealthSynchronizationSubStreamStatusCall
	GetHealthSynchronizationSubStreamStatusResponse GetHealthSynchronizationSubStreamStatusMockResponse
	GetHealthSynchronizationSubStreamTopologyMatchesCalls *[]GetHealthSynchronizationSubStreamTopologyMatchesCall
	GetHealthSynchronizationSubStreamTopologyMatchesResponse GetHealthSynchronizationSubStreamTopologyMatchesMockResponse
	PostHealthSynchronizationStreamClearErrorsCalls *[]PostHealthSynchronizationStreamClearErrorsCall
	PostHealthSynchronizationStreamClearErrorsResponse PostHealthSynchronizationStreamClearErrorsMockResponse

}	

func NewHealthSynchronizationApiMock() HealthSynchronizationApiMock {
	xDeleteHealthSynchronizationStreamCalls := make([]DeleteHealthSynchronizationStreamCall, 0)
	xGetHealthSynchronizationStreamStatusCalls := make([]GetHealthSynchronizationStreamStatusCall, 0)
	xGetHealthSynchronizationStreamTopologyMatchesCalls := make([]GetHealthSynchronizationStreamTopologyMatchesCall, 0)
	xGetHealthSynchronizationStreamsOverviewCalls := make([]GetHealthSynchronizationStreamsOverviewCall, 0)
	xGetHealthSynchronizationSubStreamOverviewCalls := make([]GetHealthSynchronizationSubStreamOverviewCall, 0)
	xGetHealthSynchronizationSubStreamStatusCalls := make([]GetHealthSynchronizationSubStreamStatusCall, 0)
	xGetHealthSynchronizationSubStreamTopologyMatchesCalls := make([]GetHealthSynchronizationSubStreamTopologyMatchesCall, 0)
	xPostHealthSynchronizationStreamClearErrorsCalls := make([]PostHealthSynchronizationStreamClearErrorsCall, 0)
	return HealthSynchronizationApiMock {
		DeleteHealthSynchronizationStreamCalls: &xDeleteHealthSynchronizationStreamCalls,
		GetHealthSynchronizationStreamStatusCalls: &xGetHealthSynchronizationStreamStatusCalls,
		GetHealthSynchronizationStreamTopologyMatchesCalls: &xGetHealthSynchronizationStreamTopologyMatchesCalls,
		GetHealthSynchronizationStreamsOverviewCalls: &xGetHealthSynchronizationStreamsOverviewCalls,
		GetHealthSynchronizationSubStreamOverviewCalls: &xGetHealthSynchronizationSubStreamOverviewCalls,
		GetHealthSynchronizationSubStreamStatusCalls: &xGetHealthSynchronizationSubStreamStatusCalls,
		GetHealthSynchronizationSubStreamTopologyMatchesCalls: &xGetHealthSynchronizationSubStreamTopologyMatchesCalls,
		PostHealthSynchronizationStreamClearErrorsCalls: &xPostHealthSynchronizationStreamClearErrorsCalls,
	}
}

type DeleteHealthSynchronizationStreamMockResponse struct {
	
	Response *_nethttp.Response
	Error error
}

type DeleteHealthSynchronizationStreamCall struct {
	PhealthStreamUrn string
}


func (mock HealthSynchronizationApiMock) DeleteHealthSynchronizationStream(ctx _context.Context, healthStreamUrn string) ApiDeleteHealthSynchronizationStreamRequest {
	return ApiDeleteHealthSynchronizationStreamRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

func (mock HealthSynchronizationApiMock) DeleteHealthSynchronizationStreamExecute(r ApiDeleteHealthSynchronizationStreamRequest) (*_nethttp.Response, error) {
	p := DeleteHealthSynchronizationStreamCall {
			PhealthStreamUrn: r.healthStreamUrn,
	}
	*mock.DeleteHealthSynchronizationStreamCalls = append(*mock.DeleteHealthSynchronizationStreamCalls, p)
	return mock.DeleteHealthSynchronizationStreamResponse.Response, mock.DeleteHealthSynchronizationStreamResponse.Error
}

type GetHealthSynchronizationStreamStatusMockResponse struct {
	Result HealthStreamStatus
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationStreamStatusCall struct {
	PhealthStreamUrn string
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamStatus(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamStatusRequest {
	return ApiGetHealthSynchronizationStreamStatusRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamStatusExecute(r ApiGetHealthSynchronizationStreamStatusRequest) (HealthStreamStatus, *_nethttp.Response, error) {
	p := GetHealthSynchronizationStreamStatusCall {
			PhealthStreamUrn: r.healthStreamUrn,
	}
	*mock.GetHealthSynchronizationStreamStatusCalls = append(*mock.GetHealthSynchronizationStreamStatusCalls, p)
	return mock.GetHealthSynchronizationStreamStatusResponse.Result, mock.GetHealthSynchronizationStreamStatusResponse.Response, mock.GetHealthSynchronizationStreamStatusResponse.Error
}

type GetHealthSynchronizationStreamTopologyMatchesMockResponse struct {
	Result TopologyMatchResult
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationStreamTopologyMatchesCall struct {
	PhealthStreamUrn string
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamTopologyMatches(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamTopologyMatchesRequest {
	return ApiGetHealthSynchronizationStreamTopologyMatchesRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error) {
	p := GetHealthSynchronizationStreamTopologyMatchesCall {
			PhealthStreamUrn: r.healthStreamUrn,
	}
	*mock.GetHealthSynchronizationStreamTopologyMatchesCalls = append(*mock.GetHealthSynchronizationStreamTopologyMatchesCalls, p)
	return mock.GetHealthSynchronizationStreamTopologyMatchesResponse.Result, mock.GetHealthSynchronizationStreamTopologyMatchesResponse.Response, mock.GetHealthSynchronizationStreamTopologyMatchesResponse.Error
}

type GetHealthSynchronizationStreamsOverviewMockResponse struct {
	Result StreamList
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationStreamsOverviewCall struct {
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamsOverview(ctx _context.Context) ApiGetHealthSynchronizationStreamsOverviewRequest {
	return ApiGetHealthSynchronizationStreamsOverviewRequest{
		ApiService: mock,
		ctx: ctx,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationStreamsOverviewExecute(r ApiGetHealthSynchronizationStreamsOverviewRequest) (StreamList, *_nethttp.Response, error) {
	p := GetHealthSynchronizationStreamsOverviewCall {
	}
	*mock.GetHealthSynchronizationStreamsOverviewCalls = append(*mock.GetHealthSynchronizationStreamsOverviewCalls, p)
	return mock.GetHealthSynchronizationStreamsOverviewResponse.Result, mock.GetHealthSynchronizationStreamsOverviewResponse.Response, mock.GetHealthSynchronizationStreamsOverviewResponse.Error
}

type GetHealthSynchronizationSubStreamOverviewMockResponse struct {
	Result SubStreamList
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationSubStreamOverviewCall struct {
	PhealthStreamUrn string
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamOverview(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationSubStreamOverviewRequest {
	return ApiGetHealthSynchronizationSubStreamOverviewRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamOverviewExecute(r ApiGetHealthSynchronizationSubStreamOverviewRequest) (SubStreamList, *_nethttp.Response, error) {
	p := GetHealthSynchronizationSubStreamOverviewCall {
			PhealthStreamUrn: r.healthStreamUrn,
	}
	*mock.GetHealthSynchronizationSubStreamOverviewCalls = append(*mock.GetHealthSynchronizationSubStreamOverviewCalls, p)
	return mock.GetHealthSynchronizationSubStreamOverviewResponse.Result, mock.GetHealthSynchronizationSubStreamOverviewResponse.Response, mock.GetHealthSynchronizationSubStreamOverviewResponse.Error
}

type GetHealthSynchronizationSubStreamStatusMockResponse struct {
	Result HealthSubStreamStatus
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationSubStreamStatusCall struct {
	PhealthStreamUrn string
	PhealthSyncSubStreamId string
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamStatus(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamStatusRequest {
	return ApiGetHealthSynchronizationSubStreamStatusRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
		healthSyncSubStreamId: healthSyncSubStreamId,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamStatusExecute(r ApiGetHealthSynchronizationSubStreamStatusRequest) (HealthSubStreamStatus, *_nethttp.Response, error) {
	p := GetHealthSynchronizationSubStreamStatusCall {
			PhealthStreamUrn: r.healthStreamUrn,
			PhealthSyncSubStreamId: r.healthSyncSubStreamId,
	}
	*mock.GetHealthSynchronizationSubStreamStatusCalls = append(*mock.GetHealthSynchronizationSubStreamStatusCalls, p)
	return mock.GetHealthSynchronizationSubStreamStatusResponse.Result, mock.GetHealthSynchronizationSubStreamStatusResponse.Response, mock.GetHealthSynchronizationSubStreamStatusResponse.Error
}

type GetHealthSynchronizationSubStreamTopologyMatchesMockResponse struct {
	Result TopologyMatchResult
	Response *_nethttp.Response
	Error error
}

type GetHealthSynchronizationSubStreamTopologyMatchesCall struct {
	PhealthStreamUrn string
	PhealthSyncSubStreamId string
}


func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamTopologyMatches(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest {
	return ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
		healthSyncSubStreamId: healthSyncSubStreamId,
	}
}

func (mock HealthSynchronizationApiMock) GetHealthSynchronizationSubStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error) {
	p := GetHealthSynchronizationSubStreamTopologyMatchesCall {
			PhealthStreamUrn: r.healthStreamUrn,
			PhealthSyncSubStreamId: r.healthSyncSubStreamId,
	}
	*mock.GetHealthSynchronizationSubStreamTopologyMatchesCalls = append(*mock.GetHealthSynchronizationSubStreamTopologyMatchesCalls, p)
	return mock.GetHealthSynchronizationSubStreamTopologyMatchesResponse.Result, mock.GetHealthSynchronizationSubStreamTopologyMatchesResponse.Response, mock.GetHealthSynchronizationSubStreamTopologyMatchesResponse.Error
}

type PostHealthSynchronizationStreamClearErrorsMockResponse struct {
	
	Response *_nethttp.Response
	Error error
}

type PostHealthSynchronizationStreamClearErrorsCall struct {
	PhealthStreamUrn string
}


func (mock HealthSynchronizationApiMock) PostHealthSynchronizationStreamClearErrors(ctx _context.Context, healthStreamUrn string) ApiPostHealthSynchronizationStreamClearErrorsRequest {
	return ApiPostHealthSynchronizationStreamClearErrorsRequest{
		ApiService: mock,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

func (mock HealthSynchronizationApiMock) PostHealthSynchronizationStreamClearErrorsExecute(r ApiPostHealthSynchronizationStreamClearErrorsRequest) (*_nethttp.Response, error) {
	p := PostHealthSynchronizationStreamClearErrorsCall {
			PhealthStreamUrn: r.healthStreamUrn,
	}
	*mock.PostHealthSynchronizationStreamClearErrorsCalls = append(*mock.PostHealthSynchronizationStreamClearErrorsCalls, p)
	return mock.PostHealthSynchronizationStreamClearErrorsResponse.Response, mock.PostHealthSynchronizationStreamClearErrorsResponse.Error
}




// HealthSynchronizationApiService HealthSynchronizationApi service
type HealthSynchronizationApiService service

type ApiDeleteHealthSynchronizationStreamRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
}


func (r ApiDeleteHealthSynchronizationStreamRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.DeleteHealthSynchronizationStreamExecute(r)
}

/*
DeleteHealthSynchronizationStream Delete health sync stream

Delete a health synchronization stream. Deletion will not be immediate.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @return ApiDeleteHealthSynchronizationStreamRequest
*/
func (a *HealthSynchronizationApiService) DeleteHealthSynchronizationStream(ctx _context.Context, healthStreamUrn string) ApiDeleteHealthSynchronizationStreamRequest {
	return ApiDeleteHealthSynchronizationStreamRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

// Execute executes the request
func (a *HealthSynchronizationApiService) DeleteHealthSynchronizationStreamExecute(r ApiDeleteHealthSynchronizationStreamRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.DeleteHealthSynchronizationStream")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthStreamNotFound
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationStreamStatusRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
}


func (r ApiGetHealthSynchronizationStreamStatusRequest) Execute() (HealthStreamStatus, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationStreamStatusExecute(r)
}

/*
GetHealthSynchronizationStreamStatus Get health sync stream status

Status overview of a single health synchronization stream

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @return ApiGetHealthSynchronizationStreamStatusRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamStatus(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamStatusRequest {
	return ApiGetHealthSynchronizationStreamStatusRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

// Execute executes the request
//  @return HealthStreamStatus
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamStatusExecute(r ApiGetHealthSynchronizationStreamStatusRequest) (HealthStreamStatus, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  HealthStreamStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationStreamStatus")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/status"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthStreamNotFound
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationStreamTopologyMatchesRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
}


func (r ApiGetHealthSynchronizationStreamTopologyMatchesRequest) Execute() (TopologyMatchResult, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationStreamTopologyMatchesExecute(r)
}

/*
GetHealthSynchronizationStreamTopologyMatches List health sync stream check-states

Overview of check-states matched to topology on the main stream.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @return ApiGetHealthSynchronizationStreamTopologyMatchesRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamTopologyMatches(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationStreamTopologyMatchesRequest {
	return ApiGetHealthSynchronizationStreamTopologyMatchesRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

// Execute executes the request
//  @return TopologyMatchResult
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  TopologyMatchResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationStreamTopologyMatches")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/topologyMatches"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthSubStreamError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationStreamsOverviewRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
}


func (r ApiGetHealthSynchronizationStreamsOverviewRequest) Execute() (StreamList, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationStreamsOverviewExecute(r)
}

/*
GetHealthSynchronizationStreamsOverview List health sync streams

Status overview of the health synchronization streams.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetHealthSynchronizationStreamsOverviewRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamsOverview(ctx _context.Context) ApiGetHealthSynchronizationStreamsOverviewRequest {
	return ApiGetHealthSynchronizationStreamsOverviewRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return StreamList
func (a *HealthSynchronizationApiService) GetHealthSynchronizationStreamsOverviewExecute(r ApiGetHealthSynchronizationStreamsOverviewRequest) (StreamList, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  StreamList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationStreamsOverview")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationSubStreamOverviewRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
}


func (r ApiGetHealthSynchronizationSubStreamOverviewRequest) Execute() (SubStreamList, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationSubStreamOverviewExecute(r)
}

/*
GetHealthSynchronizationSubStreamOverview List health sync sub-streams

Overview of all sub-streams in a certain health stream.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @return ApiGetHealthSynchronizationSubStreamOverviewRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamOverview(ctx _context.Context, healthStreamUrn string) ApiGetHealthSynchronizationSubStreamOverviewRequest {
	return ApiGetHealthSynchronizationSubStreamOverviewRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

// Execute executes the request
//  @return SubStreamList
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamOverviewExecute(r ApiGetHealthSynchronizationSubStreamOverviewRequest) (SubStreamList, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  SubStreamList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationSubStreamOverview")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/substreams"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthStreamNotFound
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationSubStreamStatusRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
	healthSyncSubStreamId string
}


func (r ApiGetHealthSynchronizationSubStreamStatusRequest) Execute() (HealthSubStreamStatus, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationSubStreamStatusExecute(r)
}

/*
GetHealthSynchronizationSubStreamStatus Get health sync sub-stream status

Status overview of a single health synchronization sub stream

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @param healthSyncSubStreamId Health synchronization sub stream id.
 @return ApiGetHealthSynchronizationSubStreamStatusRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamStatus(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamStatusRequest {
	return ApiGetHealthSynchronizationSubStreamStatusRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
		healthSyncSubStreamId: healthSyncSubStreamId,
	}
}

// Execute executes the request
//  @return HealthSubStreamStatus
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamStatusExecute(r ApiGetHealthSynchronizationSubStreamStatusRequest) (HealthSubStreamStatus, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  HealthSubStreamStatus
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationSubStreamStatus")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/substream/{healthSyncSubStreamId}/status"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"healthSyncSubStreamId"+"}", _neturl.PathEscape(parameterToString(r.healthSyncSubStreamId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthSubStreamError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
	healthSyncSubStreamId string
}


func (r ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest) Execute() (TopologyMatchResult, *_nethttp.Response, error) {
	return r.ApiService.GetHealthSynchronizationSubStreamTopologyMatchesExecute(r)
}

/*
GetHealthSynchronizationSubStreamTopologyMatches List health sync sub-stream check-states

Overview of check-states matched to topology on the main stream.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @param healthSyncSubStreamId Health synchronization sub stream id.
 @return ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest
*/
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamTopologyMatches(ctx _context.Context, healthStreamUrn string, healthSyncSubStreamId string) ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest {
	return ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
		healthSyncSubStreamId: healthSyncSubStreamId,
	}
}

// Execute executes the request
//  @return TopologyMatchResult
func (a *HealthSynchronizationApiService) GetHealthSynchronizationSubStreamTopologyMatchesExecute(r ApiGetHealthSynchronizationSubStreamTopologyMatchesRequest) (TopologyMatchResult, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  TopologyMatchResult
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.GetHealthSynchronizationSubStreamTopologyMatches")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/substream/{healthSyncSubStreamId}/topologyMatches"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"healthSyncSubStreamId"+"}", _neturl.PathEscape(parameterToString(r.healthSyncSubStreamId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthSubStreamError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPostHealthSynchronizationStreamClearErrorsRequest struct {
	ctx _context.Context
	ApiService HealthSynchronizationApi
	healthStreamUrn string
}


func (r ApiPostHealthSynchronizationStreamClearErrorsRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.PostHealthSynchronizationStreamClearErrorsExecute(r)
}

/*
PostHealthSynchronizationStreamClearErrors Clear health sync stream errors

Clear all errors for a stream and its sub-streams.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param healthStreamUrn Urn of the health stream.
 @return ApiPostHealthSynchronizationStreamClearErrorsRequest
*/
func (a *HealthSynchronizationApiService) PostHealthSynchronizationStreamClearErrors(ctx _context.Context, healthStreamUrn string) ApiPostHealthSynchronizationStreamClearErrorsRequest {
	return ApiPostHealthSynchronizationStreamClearErrorsRequest{
		ApiService: a,
		ctx: ctx,
		healthStreamUrn: healthStreamUrn,
	}
}

// Execute executes the request
func (a *HealthSynchronizationApiService) PostHealthSynchronizationStreamClearErrorsExecute(r ApiPostHealthSynchronizationStreamClearErrorsRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "HealthSynchronizationApiService.PostHealthSynchronizationStreamClearErrors")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/synchronization/health/stream/{healthStreamUrn}/clearErrors"
	localVarPath = strings.Replace(localVarPath, "{"+"healthStreamUrn"+"}", _neturl.PathEscape(parameterToString(r.healthStreamUrn, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["ApiToken"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["X-API-Token"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v InvalidUrn
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v HealthStreamNotFound
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
