/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"encoding/json"
)

// MetricTelemetry struct for MetricTelemetry
type MetricTelemetry struct {
	Type string `json:"_type"`
}

// NewMetricTelemetry instantiates a new MetricTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricTelemetry(type_ string) *MetricTelemetry {
	this := MetricTelemetry{}
	this.Type = type_
	return &this
}

// NewMetricTelemetryWithDefaults instantiates a new MetricTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricTelemetryWithDefaults() *MetricTelemetry {
	this := MetricTelemetry{}
	return &this
}

// GetType returns the Type field value
func (o *MetricTelemetry) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MetricTelemetry) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MetricTelemetry) SetType(v string) {
	o.Type = v
}

func (o MetricTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableMetricTelemetry struct {
	value *MetricTelemetry
	isSet bool
}

func (v NullableMetricTelemetry) Get() *MetricTelemetry {
	return v.value
}

func (v *NullableMetricTelemetry) Set(val *MetricTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricTelemetry(val *MetricTelemetry) *NullableMetricTelemetry {
	return &NullableMetricTelemetry{value: val, isSet: true}
}

func (v NullableMetricTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


