/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"encoding/json"
)

// StqlParsingError struct for StqlParsingError
type StqlParsingError struct {
	Type string `json:"_type"`
	Message string `json:"message"`
}

// NewStqlParsingError instantiates a new StqlParsingError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStqlParsingError(type_ string, message string) *StqlParsingError {
	this := StqlParsingError{}
	this.Type = type_
	this.Message = message
	return &this
}

// NewStqlParsingErrorWithDefaults instantiates a new StqlParsingError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStqlParsingErrorWithDefaults() *StqlParsingError {
	this := StqlParsingError{}
	return &this
}

// GetType returns the Type field value
func (o *StqlParsingError) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StqlParsingError) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StqlParsingError) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value
func (o *StqlParsingError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *StqlParsingError) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *StqlParsingError) SetMessage(v string) {
	o.Message = v
}

func (o StqlParsingError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_type"] = o.Type
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableStqlParsingError struct {
	value *StqlParsingError
	isSet bool
}

func (v NullableStqlParsingError) Get() *StqlParsingError {
	return v.value
}

func (v *NullableStqlParsingError) Set(val *StqlParsingError) {
	v.value = val
	v.isSet = true
}

func (v NullableStqlParsingError) IsSet() bool {
	return v.isSet
}

func (v *NullableStqlParsingError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStqlParsingError(val *StqlParsingError) *NullableStqlParsingError {
	return &NullableStqlParsingError{value: val, isSet: true}
}

func (v NullableStqlParsingError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStqlParsingError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


