/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"encoding/json"
)

// ElasticSearchError struct for ElasticSearchError
type ElasticSearchError struct {
	Type string `json:"_type"`
	Message string `json:"message"`
}

// NewElasticSearchError instantiates a new ElasticSearchError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElasticSearchError(type_ string, message string) *ElasticSearchError {
	this := ElasticSearchError{}
	this.Type = type_
	this.Message = message
	return &this
}

// NewElasticSearchErrorWithDefaults instantiates a new ElasticSearchError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElasticSearchErrorWithDefaults() *ElasticSearchError {
	this := ElasticSearchError{}
	return &this
}

// GetType returns the Type field value
func (o *ElasticSearchError) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ElasticSearchError) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ElasticSearchError) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value
func (o *ElasticSearchError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ElasticSearchError) GetMessageOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ElasticSearchError) SetMessage(v string) {
	o.Message = v
}

func (o ElasticSearchError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_type"] = o.Type
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableElasticSearchError struct {
	value *ElasticSearchError
	isSet bool
}

func (v NullableElasticSearchError) Get() *ElasticSearchError {
	return v.value
}

func (v *NullableElasticSearchError) Set(val *ElasticSearchError) {
	v.value = val
	v.isSet = true
}

func (v NullableElasticSearchError) IsSet() bool {
	return v.isSet
}

func (v *NullableElasticSearchError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElasticSearchError(val *ElasticSearchError) *NullableElasticSearchError {
	return &NullableElasticSearchError{value: val, isSet: true}
}

func (v NullableElasticSearchError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElasticSearchError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


