/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"encoding/json"
)

// HealthStreamMetrics1 struct for HealthStreamMetrics1
type HealthStreamMetrics1 struct {
	BucketSizeSeconds int32 `json:"bucketSizeSeconds"`
	LatencySeconds []MetricBucketValue `json:"latencySeconds,omitempty"`
	MessagePerSecond []MetricBucketValue `json:"messagePerSecond,omitempty"`
	CreatesPerSecond []MetricBucketValue `json:"createsPerSecond,omitempty"`
	UpdatesPerSecond []MetricBucketValue `json:"updatesPerSecond,omitempty"`
	DeletesPerSecond []MetricBucketValue `json:"deletesPerSecond,omitempty"`
}

// NewHealthStreamMetrics1 instantiates a new HealthStreamMetrics1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthStreamMetrics1(bucketSizeSeconds int32) *HealthStreamMetrics1 {
	this := HealthStreamMetrics1{}
	this.BucketSizeSeconds = bucketSizeSeconds
	return &this
}

// NewHealthStreamMetrics1WithDefaults instantiates a new HealthStreamMetrics1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthStreamMetrics1WithDefaults() *HealthStreamMetrics1 {
	this := HealthStreamMetrics1{}
	return &this
}

// GetBucketSizeSeconds returns the BucketSizeSeconds field value
func (o *HealthStreamMetrics1) GetBucketSizeSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BucketSizeSeconds
}

// GetBucketSizeSecondsOk returns a tuple with the BucketSizeSeconds field value
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetBucketSizeSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketSizeSeconds, true
}

// SetBucketSizeSeconds sets field value
func (o *HealthStreamMetrics1) SetBucketSizeSeconds(v int32) {
	o.BucketSizeSeconds = v
}

// GetLatencySeconds returns the LatencySeconds field value if set, zero value otherwise.
func (o *HealthStreamMetrics1) GetLatencySeconds() []MetricBucketValue {
	if o == nil || o.LatencySeconds == nil {
		var ret []MetricBucketValue
		return ret
	}
	return o.LatencySeconds
}

// GetLatencySecondsOk returns a tuple with the LatencySeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetLatencySecondsOk() ([]MetricBucketValue, bool) {
	if o == nil || o.LatencySeconds == nil {
		return nil, false
	}
	return o.LatencySeconds, true
}

// HasLatencySeconds returns a boolean if a field has been set.
func (o *HealthStreamMetrics1) HasLatencySeconds() bool {
	if o != nil && o.LatencySeconds != nil {
		return true
	}

	return false
}

// SetLatencySeconds gets a reference to the given []MetricBucketValue and assigns it to the LatencySeconds field.
func (o *HealthStreamMetrics1) SetLatencySeconds(v []MetricBucketValue) {
	o.LatencySeconds = v
}

// GetMessagePerSecond returns the MessagePerSecond field value if set, zero value otherwise.
func (o *HealthStreamMetrics1) GetMessagePerSecond() []MetricBucketValue {
	if o == nil || o.MessagePerSecond == nil {
		var ret []MetricBucketValue
		return ret
	}
	return o.MessagePerSecond
}

// GetMessagePerSecondOk returns a tuple with the MessagePerSecond field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetMessagePerSecondOk() ([]MetricBucketValue, bool) {
	if o == nil || o.MessagePerSecond == nil {
		return nil, false
	}
	return o.MessagePerSecond, true
}

// HasMessagePerSecond returns a boolean if a field has been set.
func (o *HealthStreamMetrics1) HasMessagePerSecond() bool {
	if o != nil && o.MessagePerSecond != nil {
		return true
	}

	return false
}

// SetMessagePerSecond gets a reference to the given []MetricBucketValue and assigns it to the MessagePerSecond field.
func (o *HealthStreamMetrics1) SetMessagePerSecond(v []MetricBucketValue) {
	o.MessagePerSecond = v
}

// GetCreatesPerSecond returns the CreatesPerSecond field value if set, zero value otherwise.
func (o *HealthStreamMetrics1) GetCreatesPerSecond() []MetricBucketValue {
	if o == nil || o.CreatesPerSecond == nil {
		var ret []MetricBucketValue
		return ret
	}
	return o.CreatesPerSecond
}

// GetCreatesPerSecondOk returns a tuple with the CreatesPerSecond field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetCreatesPerSecondOk() ([]MetricBucketValue, bool) {
	if o == nil || o.CreatesPerSecond == nil {
		return nil, false
	}
	return o.CreatesPerSecond, true
}

// HasCreatesPerSecond returns a boolean if a field has been set.
func (o *HealthStreamMetrics1) HasCreatesPerSecond() bool {
	if o != nil && o.CreatesPerSecond != nil {
		return true
	}

	return false
}

// SetCreatesPerSecond gets a reference to the given []MetricBucketValue and assigns it to the CreatesPerSecond field.
func (o *HealthStreamMetrics1) SetCreatesPerSecond(v []MetricBucketValue) {
	o.CreatesPerSecond = v
}

// GetUpdatesPerSecond returns the UpdatesPerSecond field value if set, zero value otherwise.
func (o *HealthStreamMetrics1) GetUpdatesPerSecond() []MetricBucketValue {
	if o == nil || o.UpdatesPerSecond == nil {
		var ret []MetricBucketValue
		return ret
	}
	return o.UpdatesPerSecond
}

// GetUpdatesPerSecondOk returns a tuple with the UpdatesPerSecond field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetUpdatesPerSecondOk() ([]MetricBucketValue, bool) {
	if o == nil || o.UpdatesPerSecond == nil {
		return nil, false
	}
	return o.UpdatesPerSecond, true
}

// HasUpdatesPerSecond returns a boolean if a field has been set.
func (o *HealthStreamMetrics1) HasUpdatesPerSecond() bool {
	if o != nil && o.UpdatesPerSecond != nil {
		return true
	}

	return false
}

// SetUpdatesPerSecond gets a reference to the given []MetricBucketValue and assigns it to the UpdatesPerSecond field.
func (o *HealthStreamMetrics1) SetUpdatesPerSecond(v []MetricBucketValue) {
	o.UpdatesPerSecond = v
}

// GetDeletesPerSecond returns the DeletesPerSecond field value if set, zero value otherwise.
func (o *HealthStreamMetrics1) GetDeletesPerSecond() []MetricBucketValue {
	if o == nil || o.DeletesPerSecond == nil {
		var ret []MetricBucketValue
		return ret
	}
	return o.DeletesPerSecond
}

// GetDeletesPerSecondOk returns a tuple with the DeletesPerSecond field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthStreamMetrics1) GetDeletesPerSecondOk() ([]MetricBucketValue, bool) {
	if o == nil || o.DeletesPerSecond == nil {
		return nil, false
	}
	return o.DeletesPerSecond, true
}

// HasDeletesPerSecond returns a boolean if a field has been set.
func (o *HealthStreamMetrics1) HasDeletesPerSecond() bool {
	if o != nil && o.DeletesPerSecond != nil {
		return true
	}

	return false
}

// SetDeletesPerSecond gets a reference to the given []MetricBucketValue and assigns it to the DeletesPerSecond field.
func (o *HealthStreamMetrics1) SetDeletesPerSecond(v []MetricBucketValue) {
	o.DeletesPerSecond = v
}

func (o HealthStreamMetrics1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bucketSizeSeconds"] = o.BucketSizeSeconds
	}
	if o.LatencySeconds != nil {
		toSerialize["latencySeconds"] = o.LatencySeconds
	}
	if o.MessagePerSecond != nil {
		toSerialize["messagePerSecond"] = o.MessagePerSecond
	}
	if o.CreatesPerSecond != nil {
		toSerialize["createsPerSecond"] = o.CreatesPerSecond
	}
	if o.UpdatesPerSecond != nil {
		toSerialize["updatesPerSecond"] = o.UpdatesPerSecond
	}
	if o.DeletesPerSecond != nil {
		toSerialize["deletesPerSecond"] = o.DeletesPerSecond
	}
	return json.Marshal(toSerialize)
}

type NullableHealthStreamMetrics1 struct {
	value *HealthStreamMetrics1
	isSet bool
}

func (v NullableHealthStreamMetrics1) Get() *HealthStreamMetrics1 {
	return v.value
}

func (v *NullableHealthStreamMetrics1) Set(val *HealthStreamMetrics1) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthStreamMetrics1) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthStreamMetrics1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthStreamMetrics1(val *HealthStreamMetrics1) *NullableHealthStreamMetrics1 {
	return &NullableHealthStreamMetrics1{value: val, isSet: true}
}

func (v NullableHealthStreamMetrics1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthStreamMetrics1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


