/*
StackState API

StackState's API specification

API version: 0.0.1
Contact: info@stackstate.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stackstate_client

import (
	"encoding/json"
)

// TopologyStreamMetrics struct for TopologyStreamMetrics
type TopologyStreamMetrics struct {
	BucketSizeSeconds int32 `json:"bucketSizeSeconds"`
	LatencySeconds *[]MetricBucketValue `json:"latencySeconds,omitempty"`
}

// NewTopologyStreamMetrics instantiates a new TopologyStreamMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopologyStreamMetrics(bucketSizeSeconds int32) *TopologyStreamMetrics {
	this := TopologyStreamMetrics{}
	this.BucketSizeSeconds = bucketSizeSeconds
	return &this
}

// NewTopologyStreamMetricsWithDefaults instantiates a new TopologyStreamMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopologyStreamMetricsWithDefaults() *TopologyStreamMetrics {
	this := TopologyStreamMetrics{}
	return &this
}

// GetBucketSizeSeconds returns the BucketSizeSeconds field value
func (o *TopologyStreamMetrics) GetBucketSizeSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BucketSizeSeconds
}

// GetBucketSizeSecondsOk returns a tuple with the BucketSizeSeconds field value
// and a boolean to check if the value has been set.
func (o *TopologyStreamMetrics) GetBucketSizeSecondsOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BucketSizeSeconds, true
}

// SetBucketSizeSeconds sets field value
func (o *TopologyStreamMetrics) SetBucketSizeSeconds(v int32) {
	o.BucketSizeSeconds = v
}

// GetLatencySeconds returns the LatencySeconds field value if set, zero value otherwise.
func (o *TopologyStreamMetrics) GetLatencySeconds() []MetricBucketValue {
	if o == nil || o.LatencySeconds == nil {
		var ret []MetricBucketValue
		return ret
	}
	return *o.LatencySeconds
}

// GetLatencySecondsOk returns a tuple with the LatencySeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopologyStreamMetrics) GetLatencySecondsOk() (*[]MetricBucketValue, bool) {
	if o == nil || o.LatencySeconds == nil {
		return nil, false
	}
	return o.LatencySeconds, true
}

// HasLatencySeconds returns a boolean if a field has been set.
func (o *TopologyStreamMetrics) HasLatencySeconds() bool {
	if o != nil && o.LatencySeconds != nil {
		return true
	}

	return false
}

// SetLatencySeconds gets a reference to the given []MetricBucketValue and assigns it to the LatencySeconds field.
func (o *TopologyStreamMetrics) SetLatencySeconds(v []MetricBucketValue) {
	o.LatencySeconds = &v
}

func (o TopologyStreamMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bucketSizeSeconds"] = o.BucketSizeSeconds
	}
	if o.LatencySeconds != nil {
		toSerialize["latencySeconds"] = o.LatencySeconds
	}
	return json.Marshal(toSerialize)
}

type NullableTopologyStreamMetrics struct {
	value *TopologyStreamMetrics
	isSet bool
}

func (v NullableTopologyStreamMetrics) Get() *TopologyStreamMetrics {
	return v.value
}

func (v *NullableTopologyStreamMetrics) Set(val *TopologyStreamMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTopologyStreamMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTopologyStreamMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopologyStreamMetrics(val *TopologyStreamMetrics) *NullableTopologyStreamMetrics {
	return &NullableTopologyStreamMetrics{value: val, isSet: true}
}

func (v NullableTopologyStreamMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopologyStreamMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


